module.exports = {
    DISCUSSION_TIME: 60,
    VOTING_TIME: 30,
    RESULT_TIME: 5,
    ROOM_CODE_LENGTH: 6,
    MAX_PLAYERS: 20,
    MIN_PLAYERS: 3,
    RECONNECT_GRACE_PERIOD_MS: 60000,
    CHAT_COOLDOWN_MS: 500,
    MAX_CHAT_LENGTH: 150,
    MAX_NAME_LENGTH: 16
};
